"""Local process adapter for offline report execution."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from mlquant.factor_store import FactorStore


def start_report(root: Path, report_id: str) -> dict[str, Any]:
    with FactorStore.from_root(root) as store:
        row = store.report_detail(report_id)
        if row["status"] != "queued":
            raise ValueError(f"Report is not queued: {report_id} ({row['status']})")
        # UUID generated by FactorStore, never use a caller-controlled path segment.
        log_dir = root / "factor_library" / "logs"
        log_dir.mkdir(parents=True, exist_ok=True)
        log = log_dir / f"report-{row['report_id']}.log"
        try:
            with log.open("ab") as stream:
                process = subprocess.Popen(
                    [sys.executable, "-m", "mlquant", "report", "run",
                     "--root", str(root), "--report-id", report_id, "--json"],
                    stdin=subprocess.DEVNULL, stdout=stream, stderr=stream,
                    creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
                    start_new_session=sys.platform != "win32",
                    env={**os.environ, "PYTHONIOENCODING": "utf-8"},
                )
        except OSError as error:
            store.set_report_status(report_id, "failed", error=str(error))
            raise
    return {"report_id": report_id, "status": "queued", "pid": process.pid, "log": str(log)}
